### PR TITLE
Snapshot Queries For Merkle Allowlists

### PR DESCRIPTION
**Pull request by mchrupcala**
Artists with merkle-minter projects will need a way to query a list of users from our subgraph & export a .csv so they can import to their project shell. This new script will pull all holders of AB + Collab projects (or just all AB projects), and can be easily modified to add/remove core contracts as we need. 

I decided to add this as a new file because 1) we needed separate logic for the accounts-querying that the contract_in subgraph query logic is using (our old script queries for tokens) and 2) the old file's unchanged (in case artists are still using it) 

P.S. CSV files are uploading to the artist dashboard with whitespace instead of as a comma-separated list so I [added a ticket](https://app.asana.com/0/1202536410781342/1203326678323136) to fix that soon.
Screen Shot 2022-11-07 at 7 47 38 PM

Ticket: https://app.asana.com/0/1201511168382186/1203266067371008

### CODE REVIEW

**Review by jakerockland — CHANGES_REQUESTED** [review]
IIUC @mchrupcala, this updated script is not actually making use of `projectIDFilter` at all, and thus also not allowing for usage of the project filtering functionality. 

> 2) the old file's unchanged (in case artists are still using it)

Also re: not just diffing the old script, I don't think this is right–IIUC the updated script should be able to be at feature parity (with new functionality added) with the old script, so we should be able to just make a modification here rather than creating a whole new script.

**Comment by mchrupcala** [comment]
> IIUC @mchrupcala, this updated script is not actually making use of projectIDFilter at all, and thus also not allowing for usage of the project filtering functionality.

Yes sorry, must've missed that! I should've left this as a draft - was planning to take another look at this in the morning.

> Also re: not just diffing the old script, I don't think this is right–IIUC the updated script should be able to be at feature parity (with new functionality added) with the old script, so we should be able to just make a modification here rather than creating a whole new script.

At first I was updating the old script but I noticed it uses a completely different format (it collects all the held projectIDs on a per-user basis). These formats seemed different enough to warrant a new script for simply dumping the wallet addresses in one long list to match our merkle allowlists. But tbh I don't have context around how artists use the old script currently, so I'll defer to whether ya'll think we should offer both types of lists or overwrite the earlier version.

Screen Shot 2022-11-07 at 11 30 40 PM

**Comment by jakerockland** [comment]
> At first I was updating the old script but I noticed it uses a completely different format (it collects all the held projectIDs on a per-user basis). These formats seemed different enough to warrant a new script for simply dumping the wallet addresses in one long list to match our merkle allowlists. But tbh I don't have context around how artists use the old script currently, so I'll defer to whether ya'll think we should offer both types of lists or overwrite the earlier version.

I see I see I see – in this case, I think folks will still be able to find the old version via repo history and that it is more confusing to have both than to just diff. Let's just edit existing script for now, and if we get any pushback / etc. from artists we can always dig up the old one and move to a new file in the future.

**Comment by mchrupcala** [comment]
> I see I see I see – in this case, I think folks will still be able to find the old version via repo history and that it is more confusing to have both than to just diff. Let's just edit existing script for now, and if we get any pushback / etc. from artists we can always dig up the old one and move to a new file in the future.

Sounds great! I deleted the new copy of this script and updated the old one so that it can filter in/out the various core contracts via `CORE_CONTRACTS` param.

For allowlists, we can just advise artists to  use `ArtBlocksTokenHolders_OwnersOnly.csv` and to delete the Owner header (otherwise our form validation will flash an error). After that's done they'll be able to upload to our artist dashboard - should be straightforward.

**Comment by jakerockland** [comment]
> > I see I see I see – in this case, I think folks will still be able to find the old version via repo history and that it is more confusing to have both than to just diff. Let's just edit existing script for now, and if we get any pushback / etc. from artists we can always dig up the old one and move to a new file in the future.
> 
> Sounds great! I deleted the new copy of this script and updated the old one so that it can filter in/out the various core contracts via `CORE_CONTRACTS` param.
> 
> For allowlists, we can just advise artists to use `ArtBlocksTokenHolders_OwnersOnly.csv` and to delete the Owner header (otherwise our form validation will flash an error). After that's done they'll be able to upload to our artist dashboard - should be straightforward.

That SGTM @mchrupcala – changes LGTM, but could we update the associated readme as well please (found here: https://github.com/ArtBlocks/artblocks-community-tooling/tree/main/SnapshotABHolders#readme) potentially adding some of these details as well as to how this can be used alongside the allowlist minter?

**Review by jakerockland — APPROVED** [review]

**Comment by jakerockland** [comment]
cc @aaronpenne just for vis on this, in case this tool is useful script reference for future DE.

**Review by ryley-o — APPROVED** [review]
This is great, thank you for updating! ++ to readme updates, maybe a paragraph explaining how to easily filter to a couple of projects (guessing that will be a common use case) 🎉

**Comment by mchrupcala** [comment]
> That SGTM @mchrupcala – changes LGTM, but could we update the associated readme as well please (found here: https://github.com/ArtBlocks/artblocks-community-tooling/tree/main/SnapshotABHolders#readme) potentially adding some of these details as well as to how this can be used alongside the allowlist minter?

Sounds great! The [readme's been updated ](https://github.com/ArtBlocks/artblocks-community-tooling/blob/94656c1b7689cce52b0ab78752e6cffd2be0a30d/SnapshotABHolders/readme.md)with more background & examples/instructions. I'll add some of this to our docs as well. 
@jakerockland @ryley-o

**Pull request merged**
